### ISSUE TITLE
Code doesn't build on OpenSSL 3.0

### ISSUE THREAD

**Issue by daleglass** [vircadia/vircadia#1646]
This happens on Linux:

```
[100%] Linking CXX executable interface
/usr/bin/ld: ../libraries/networking/libnetworking.so: undefined reference to `SSL_get_peer_certificate'
/usr/bin/ld: ../libraries/networking/libnetworking.so: undefined reference to `EVP_MD_size'
/usr/bin/ld: ../libraries/networking/libnetworking.so: undefined reference to `EVP_MD_type'
collect2: error: ld returned 1 exit status
```

but I expect the same would be the case on any other OS. Seems like it should be an easy fix.

**Comment by daleglass** [comment]
Darn. It seems this is a webrtc issue.

**Comment by pauleheister** [comment]
Hello. 
I am new to Vircadia and I have the same Issue on Arch Linux. I don't know how to solve this. Maybe someone can help.
