### PR TITLE
Create skeleton of the native client library and Unity SDK.

### PR DESCRIPTION
**Pull request by namark**
- [x] Basic setup.
  - [x] SDK library setup as a dependency for the interface.
  - [x] Example C API that can be used in a Unity3D plugin.
- [x] Documentation.
  - [x] CMake configuration for doxygen.
  - [x] Example API Documentation.
- [x] Unit Tests.
  - [x] VCPKG and Cmake configuration for Catch2.
  - [x] Example API Unit Tests.
- [x] Unity3D plugin skeleton (in a separate [repo](https://github.com/vircadia/vircadia-unity-sdk))
  - [x] Example C API integration.
  - [x] Example unit tests.
  - [x] API documentation setup.
- [x] Example project that includes the Unity plugin and makes use of the example C# API.
- [x] Project setup and build instructions for all components.

The example project is included in the SDK repo. The SDK itself is set up as a package, which is not by itself a Unity project, it needs to be imported(or in this case technically embedded) into a project to be worked on, so it doesn't really make sense to have a separate example repo.

### CODE REVIEW

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-7fac14e-.tar_59d7c88f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-7fac14e-.tar_59d7c88f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-7fac14e-_59d7c88f.sh

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-7fac14e-_59d7c88f.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-7fac14e-_59d7c88f.dmg

**build (self-hosted_debian-11_aarch64, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-7fac14e-.tar_59d7c88f.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-7fac14e-.tar_59d7c88f.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-7fac14e-_59d7c88f.sh

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-28c22e1-.tar_5e8ae2e0.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-28c22e1-.tar_5e8ae2e0.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-28c22e1-_5e8ae2e0.sh

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-28c22e1-_5e8ae2e0.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-28c22e1-_5e8ae2e0.dmg

**build (windows-latest, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-28c22e1-_5e8ae2e0.exe

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-390b570-_5e8ae2e0.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-390b570-.tar_5e8ae2e0.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-390b570-.tar_5e8ae2e0.Z

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-390b570-_5e8ae2e0.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-390b570-_5e8ae2e0.dmg

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-d430c36-_9049c81c.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-d430c36-_9049c81c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-d430c36-.tar_9049c81c.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-d430c36-_9049c81c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-d430c36-.tar_9049c81c.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-36f8d32-_021ecff4.dmg

**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-36f8d32-_021ecff4.dmg

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-36f8d32-_021ecff4.exe

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-36f8d32-_021ecff4.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-36f8d32-.tar_021ecff4.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-36f8d32-.tar_021ecff4.gz

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-26d4674-_c2f37f1c.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-26d4674-_c2f37f1c.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-26d4674-.tar_c2f37f1c.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-26d4674-.tar_c2f37f1c.Z

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-26d4674-_c2f37f1c.dmg

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-26d4674-_c2f37f1c.exe

File: cmake/ports/hifi-deps/CONTROL [hunk 1]
```diff
@@ -1,4 +1,4 @@
 Source: hifi-deps
 Version: 0.1.5-github-actions
 Description: Collected dependencies for High Fidelity applications
-Build-Depends: bullet3, draco, etc2comp, glad, glm, nvtt, openexr (!android), openssl (windows), opus, polyvox, tbb (!android), vhacd, webrtc (!android|!(linux&arm)), zlib
+Build-Depends: bullet3, draco, etc2comp, glad, glm, nvtt, openexr (!android), openssl (windows), opus, polyvox, tbb (!android), vhacd, webrtc (!android|!(linux&arm)), zlib, catch2
```
Comment (ctrlaltdavid) [inline cmake/ports/hifi-deps/CONTROL:4]:
```suggestion
Build-Depends: bullet3, catch2, draco, etc2comp, glad, glm, nvtt, openexr (!android), openssl (windows), opus, polyvox, tbb (!android), vhacd, webrtc (!android|!(linux&arm)), zlib
```
In alphabetical order.

File: libraries/vircadia-client/src/common.h [hunk 2]
```diff
@@ -0,0 +1,24 @@
+//
+//  common.h
+//  libraries/client/src
+//
+//  Created by Nshan G. on 1 March 2022.
+//  Copyright 2022 Vircadia contributors.
+//
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/src/common.h:7]:
```suggestion
//  Copyright 2022 Vircadia contributors.
//
//  Distributed under the Apache License, Version 2.0.
//  See the accompanying file LICENSE or http://www.apache.org/licenses/LICENSE-2.0.html
//
```
Missing license lines, here and elsewhere.

File: libraries/vircadia-client/tests/version.cpp [hunk 3]
```diff
@@ -0,0 +1,28 @@
+#include <../src/version.h>
+
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/tests/version.cpp:2]: Copyright etc. header missing.

File: libraries/vircadia-client/src/common.h [hunk 4]
```diff
@@ -0,0 +1,24 @@
...
+#ifdef VIRCADIA_CLIENT_DLL_EXPORT
+/* We are building this library */
+#   define VIRCADIA_CLIENT_DYN_API extern "C" __declspec(dllexport)
+#else
+/* We are using this library */
+#   define VIRCADIA_CLIENT_DYN_API  extern "C" __declspec(dllimport)
+#endif
+#else
+    #define VIRCADIA_CLIENT_DYN_API extern "C"
+#endif
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/src/common.h:22]:
```suggestion
#if defined(_MSC_VER)
    #ifdef VIRCADIA_CLIENT_DLL_EXPORT
        /* We are building this library */
        #   define VIRCADIA_CLIENT_DYN_API extern "C" __declspec(dllexport)
    #else
        /* We are using this library */
        #   define VIRCADIA_CLIENT_DYN_API  extern "C" __declspec(dllimport)
    #endif
#else
    #define VIRCADIA_CLIENT_DYN_API extern "C"
#endif
```

File: libraries/vircadia-client/src/version.h [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+
+/**
+ * \brief Defines the layout of version information returned by vircadia_client_version().
+ */
+struct vircadia_client_version_data {
+
+    /** \brief The major version number.
+     *
+     * Increments on compatibility breaking changes.
+     */
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/src/version.h:24]: Is the client version of the form "2022.1.0"? If so, the doxygen needs updating: major = year; minor = breaking change; ...

File: libraries/vircadia-client/src/version.h [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+/** \file */
+
+#ifndef VIRCADIA_LIBRARIES_CLIENT_SRC_VERSION_H
+#define VIRCADIA_LIBRARIES_CLIENT_SRC_VERSION_H
+
+#include "common.h"
+
+/**
+ * \brief Defines the layout of version information returned by vircadia_client_version().
+ */
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/src/version.h:18]:
```suggestion
/// @brief Defines the layout of version information returned by vircadia_client_version().
```
The rest of the source uses the "/// @" style of Doxygen comment and is processed by running the following command in the /tools/doxygen directory:
```
doxygen DoxyFile
```

File: libraries/vircadia-client/tests/version.cpp [hunk 7]
```diff
@@ -0,0 +1,28 @@
...
+    REQUIRE( (version.major != 0 || version.minor != 0 || version.tweak != 0) );
+
+    REQUIRE( version.commit != ""s );
+    REQUIRE( version.number != ""s );
+    REQUIRE( version.full != ""s );
+
+    auto number = "v"s + std::to_string(version.major)
+        + "."s + std::to_string(version.minor)
+        + "."s + std::to_string(version.tweak)
+    ;
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/tests/version.cpp:24]:
```suggestion
        + "."s + std::to_string(version.tweak);

```

File: libraries/vircadia-client/tests/version.cpp [hunk 8]
```diff
@@ -0,0 +1,28 @@
...
+using namespace std::literals;
+
+TEST_CASE( "Sanity checks for client API version information.", "[client-api-version]" ) {
+
+    auto version = *vircadia_client_version();
+
+    REQUIRE( version.major >= 0 );
+    REQUIRE( version.minor >= 0 );
+    REQUIRE( version.tweak >= 0 );
+    REQUIRE( (version.major != 0 || version.minor != 0 || version.tweak != 0) );
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/tests/version.cpp:15]:
```suggestion
    REQUIRE(version.major != 0 || version.minor != 0 || version.tweak != 0);
```
Unnecessary parentheses.

File: libraries/vircadia-client/tests/version.cpp [hunk 9]
```diff
@@ -0,0 +1,28 @@
...
+    REQUIRE( version.commit != ""s );
+    REQUIRE( version.number != ""s );
+    REQUIRE( version.full != ""s );
+
+    auto number = "v"s + std::to_string(version.major)
+        + "."s + std::to_string(version.minor)
+        + "."s + std::to_string(version.tweak)
+    ;
+    REQUIRE(version.number == number);
+    REQUIRE(version.full == version.number + "-git."s + version.commit);
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/tests/version.cpp:26]: Inconsistent whitespace c.f. previous REQUIRE statements.

File: libraries/vircadia-client/tests/version.cpp [hunk 10]
```diff
@@ -0,0 +1,28 @@
+#include <../src/version.h>
+
+#include <catch2/catch.hpp>
+#include <string>
+
+using namespace std::literals;
+
+TEST_CASE( "Sanity checks for client API version information.", "[client-api-version]" ) {
```
Comment (ctrlaltdavid) [inline libraries/vircadia-client/tests/version.cpp:8]:
```suggestion
TEST_CASE("Sanity checks for client API version information.", "[client-api-version]") {
```
Unnecessary whitespace here and in REQUIRE statements below.

**Review by ctrlaltdavid — CHANGES_REQUESTED** [review]

**Comment by ctrlaltdavid** [comment]
The Vircadia Unity SDK repo should be transferred from https://github.com/namark/vircadia-unity-sdk to Vircadia.

I've reviewed the code but haven't built and run it, the tests, or the Unity plugin.

File: libraries/vircadia-client/src/version.h (hunk 6 above)
Comment (namark) [reply libraries/vircadia-client/src/version.h]: Comment style fixed. The client API documentation can also be built separately with CMake (the Doxyfile is auto-generated), so added instruction for that in the readme.

File: libraries/vircadia-client/tests/version.cpp (hunk 8 above)
Comment (namark) [reply libraries/vircadia-client/tests/version.cpp]: These are actually required by catch2 in this case, otherwise it complains:
`catch2/catch.hpp:2251:44: error: static assertion failed: chained comparisons are not supported inside assertions, wrap the expression inside parentheses, or decompose it`
I guess has something to do with the use of macros.

File: libraries/vircadia-client/tests/version.cpp (hunk 9 above)
Comment (namark) [reply libraries/vircadia-client/tests/version.cpp:37]: Left unchanged in favor of the other change request to remove whitespace in the other statements.

**Comment by namark** [comment]
Forked the unity sdk repo https://github.com/vircadia/vircadia-unity-sdk

File: libraries/vircadia-client/src/version.h (hunk 5 above)
Comment (namark) [reply libraries/vircadia-client/src/version.h]: Well, this is not set in stone yet, just example of what it might look like. I'm not sure I understand that specific versioning scheme enough to document and use it properly.

Comment (ctrlaltdavid) [reply libraries/vircadia-client/src/version.h]: The versioning scheme used by Vircadia, the Web SDK, and the Web app is yyyy,m,n:
- yyyy = The year of the release.
- m = Major release. An increment in this indicates a breaking change (e.g., Vircadia protocol change).
- n = Minor release. Normal, non-breaking changes.

Comment (namark) [reply libraries/vircadia-client/src/version.h]: Does the year change with either a major or a minor release, or do we wait for a major release to update it?

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-2d33096-_015c2f3b.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-2d33096-_015c2f3b.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-2d33096-.tar_015c2f3b.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-2d33096-_015c2f3b.sh
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-2d33096-.tar_015c2f3b.Z

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-2d33096-_015c2f3b.exe

File: libraries/vircadia-client/src/version.h (hunk 5 above)
Comment (ctrlaltdavid) [reply libraries/vircadia-client/src/version.h]: The year changes whenever the first release of the new year occurs.

Comment (namark) [reply libraries/vircadia-client/src/version.h]: Updated the code and the docs to reflect this, both here and in the unity sdk repo.

**Comment by vircadia-build-notifier** [comment]
The following links are available: 
**build (macOS-10.15, client)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-Interface-PR1607-e0c4771-_ee502694.dmg

**build (macOS-10.15, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-e0c4771-_ee502694.dmg

**build (ubuntu-18.04, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-e0c4771-.tar_ee502694.gz
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-e0c4771-.tar_ee502694.Z
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-e0c4771-_ee502694.sh

**build (windows-2019, full)**
 - https://athena-public.s3.eu-west-3.amazonaws.com/builds/PR/vircadia_vircadia/PR1607/Vircadia-PR1607-e0c4771-_ee502694.exe

**Review by ctrlaltdavid — APPROVED** [review]
